title: Youhyun Sung
url: "https://github.com/youhyunsung"
baseurl: ""

markdown: kramdown
ins_logo: "./hanyang_logo.png"

tracking_id: UA-138665784-2 #


footer: yes
footer_url: "https://github.com/youhyunsung"
footer_text: "Youhyun Sung"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: ""
 - name: "CV"
   link: "https://drive.google.com/file/d/1SPQxUf3E292aOiAJeoGpxWQL78539vQ9/view?usp=sharing" #"Curriculum_Vitae_Chanjunpark.pdf"

remote_theme: ankitsultana/researcher@gem

theme: jekyll-theme-cayman
